spring:
  application:
    name: backend-item
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

FTP_HOST: 192.168.1.99
FTP_PORT: 21
FTP_USERNAME: ftpuser
FTP_PASSWORD: ftpuser
FTP_BASEPATH: /home/ftpuser/

tx-lcn:
  client:
    manager-address: 192.168.1.99:8070