spring:
  application:
    name: backend-item
server:
  port: 9020
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

FTP_HOST: 192.168.70.144
FTP_PORT: 21
FTP_USERNAME: ftpuser
FTP_PASSWORD: ftpuser
FTP_BASEPATH: /home/ftpuser/
