spring:
  application:
    name: common-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_shop?characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9010
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

tx-lcn:
  client:
    manager-address: http://localhost:8070

